
include:
  - ../elastic+filebeat+sshd/docker-compose.single-node.yml

services:
  elastalert:
    depends_on:
      es01:
        condition: service_healthy
    image: jertel/elastalert2
    volumes:
      - type: "bind"
        source: "./storage/elastalert/config.yaml"
        target: "/opt/elastalert/config.yaml"
      - type: "bind"
        source: "./storage/elastalert/rules"
        target: "/opt/elastalert/rules"
